import { GITHUB_CI_TEMPLATE, type RemoteSpec } from '../types';

/**
 * CI is governance, not per-team plumbing: every remote extends ONE central
 * reusable pipeline. The generated file carries only identity inputs.
 */
export function githubWorkflow(spec: RemoteSpec): string {
  return `# Auto-generated by create-mission-remote.
#
# Do NOT add bespoke build/test/deploy steps here. All pipeline logic lives in
# the central reusable workflow (platform-tooling) so every remote ships the
# same way. Need a new step? Propose it against mission-ci-template.yml.
name: deploy

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  mission-ci:
    uses: ${GITHUB_CI_TEMPLATE}
    with:
      remote-name: ${spec.name}
      framework: ${spec.framework}
      port: ${spec.port}
    secrets: inherit
`;
}

export function gitlabCi(spec: RemoteSpec): string {
  return `# Auto-generated by create-mission-remote.
#
# Do NOT add bespoke stages here — all pipeline logic lives in the central
# template (platform-tooling). Need a new step? Propose it there.
include:
  - project: 'mission-control-org/platform-tooling'
    ref: main
    file: '/ci/mission-ci-template.yml'

variables:
  REMOTE_NAME: '${spec.name}'
  FRAMEWORK: '${spec.framework}'
  PORT: '${spec.port}'
`;
}

export function ciFile(spec: RemoteSpec): { path: string; contents: string } {
  return spec.ci === 'gitlab'
    ? { path: '.gitlab-ci.yml', contents: gitlabCi(spec) }
    : { path: '.github/workflows/deploy.yml', contents: githubWorkflow(spec) };
}
