import { FRAMEWORK_LABELS, MCP_SERVER_URL, type RemoteSpec } from '../types';

export function tsconfig(spec: RemoteSpec): string {
  const base: Record<string, unknown> = {
    strict: true,
    target: 'ES2022',
    module: 'ESNext',
    moduleResolution: 'bundler',
    lib: ['ES2022', 'DOM', 'DOM.Iterable'],
    skipLibCheck: true,
    esModuleInterop: true,
    forceConsistentCasingInFileNames: true,
    isolatedModules: true,
    resolveJsonModule: true,
    noEmit: true,
  };

  if (spec.framework === 'react') {
    base.jsx = 'react-jsx';
  }
  if (spec.framework === 'svelte') {
    base.verbatimModuleSyntax = true;
  }
  if (spec.framework === 'angular') {
    // The Angular compiler requires classic class-field semantics.
    base.useDefineForClassFields = false;
    base.experimentalDecorators = true;
  }

  const config: Record<string, unknown> = {
    compilerOptions: base,
    include: ['src'],
  };
  if (spec.framework === 'angular') {
    config.angularCompilerOptions = { strictTemplates: true };
  }

  return `${JSON.stringify(config, null, 2)}\n`;
}

export function gitignore(): string {
  return `node_modules/
dist/
# MF 2.0 generated remote types (hand-declared types are the convention here)
@mf-types/
*.log
.DS_Store
`;
}

export function remoteReadme(spec: RemoteSpec): string {
  const surface = spec.framework === 'angular' ? './routes' : './mount';
  return `# ${spec.name}

Mission Control remote — ${FRAMEWORK_LABELS[spec.framework]}, Module Federation 2.0, port ${spec.port}.
Generated by \`create-mission-remote\`.

## Commands

\`\`\`bash
pnpm install
pnpm dev         # standalone dev on http://localhost:${spec.port} (local dev bridge)
pnpm build       # production bundle + dist/mf-manifest.json
pnpm typecheck
\`\`\`

## How this remote fits the platform

- **Federation surface:** \`${surface}\` (declared in \`rsbuild.config.ts\`). The
  shell consumes it via \`${spec.mfName}@http://localhost:${spec.port}/mf-manifest.json\`.
- **Global state:** ONLY through \`@teradata-pe/bridge\` (\`getBridge()\`). Session,
  theme, events, shared data and tasks are host-owned contracts.
- **Build policy:** owned by \`@mission/rsbuild-${spec.framework}\` — shared
  singleton map, CORS, assetPrefix and manifest emission are not configured here.
- **CI:** the pipeline file only extends the central platform template.

## For AI agents

Read \`CLAUDE.md\` / \`.cursorrules\` before changing anything, and connect to
the platform MCP server at \`${MCP_SERVER_URL}\` for live architectural
context (contracts, cache keys, federation graph).
`;
}
